### ISSUE TITLE
Error `@badeball/cypress-cucumber-preprocessor` 18.0.4 expects node v18

### ISSUE THREAD

**Issue by dholman7** [Qytera-Gmbh/cypress-xray-plugin#152]
I am receiving this error in node v16.20.0 for "cypress-xray-plugin": "4.0.1". The documentation states v15 or above is required.
```
error @badeball/cypress-cucumber-preprocessor@18.0.4: The engine "node" is incompatible with this module. Expected version ">=18.0.0". Got "16.20.0"
error Found incompatible module
```

Installing node v18 resolves the issue but is incompatible with many of my projects.

**Comment by RenanPaixao** [comment]
I also had this same problem, and I want to use only cypress for tests, no cucumber.

**Comment by dholman7** [comment]
I am using plain Cypress tests as well. Thanks for the quick response!

**Comment by csvtuda** [comment]
Hey @dholman7 @RenanPaixao,

version `4.0.2` should now address your problems regarding the unwanted Cucumber preprocessor dependency. I have moved it to the optional dependencies, meaning that an install failure because of conflicting node versions should now simply result in the preprocessor not being installed at all (without warning).

If you're not running any Cucumber feature files, you should not notice any change.

**Comment by RenanPaixao** [comment]
Hi @csvtuda. The new version is not requiring the cucumber preprocessor dependency anymore, as expected. Good job!

But yesterday I was using the `3.3.3` version and the results were being upload without problems, but in the new version I'm facing upload skips. Do you know anything about it?

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/57810270/f1dd8550-c87a-43e5-909e-d65b7e3dadfc)

**Comment by csvtuda** [comment]
I actually forgot to close this issue. So I'm closing it now.
