### ISSUE TITLE
Are there any plans to add more features around updating test steps?

### ISSUE THREAD

**Issue by reify-emmanuel-malave** [Qytera-Gmbh/cypress-xray-plugin#169]
Hello, I have really enjoyed using this plugin for my Cypress/X-Ray integration. Thank you for your work! The update test step feature flag gives a quick solution to generate test step information. I was wondering if there are any plans to expand this update test step functionality. Some things that would be useful for me would be: 
- The ability to update the text within the test step with exactly what I want, not just a copy of the code 
- The ability to update multiple test steps within a test 
- The ability to update the data and expected result fields within the test steps

**Comment by csvtuda** [comment]
Hey,

these are all good ideas, thank you. Actually, I've often thought about more advanced test step integrations, it's obviously not a good solution with the test code as one big step right now.

I'd love to somehow address all your three wishes, but the problem is that Cypress does not really fit into Xray's step scheme. Cypress just does not have a notion of a _step_, it's more or less simply one huge chain of actions.

<hr/>

The only somewhat feasible solution I could think of is providing custom commands like:

```ts
cy.step("Click login button", () => {
  cy.get("#login").click();
  cy.get("#login").should("not.exist");
});
```

but it feels like a lot of overhead. Even more so when expected and actual results need to be integrated as well. I have no idea how I would even access assertions like above to extract actual and expected values, apart from providing a wrapper around Cypress's assertions (more overhead).

I haven't been able to figure it out yet, but I'm open for ideas!

**Comment by csvtuda** [comment]
With the release of Cypress v13, not even the test function's body is accessible to the plugin anymore. I've therefore decided to remove the step updates entirely (see [here](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#500)).

This means that from now on, the plugin will never update test steps of manual test cases again. I think taking my explanation above into account, this pretty much closes your request.
