### ISSUE TITLE
Repository issue is cleaned

### ISSUE THREAD

**Issue by art-emm** [Qytera-Gmbh/cypress-xray-plugin#264]
### Description

Hello! 
I have xray repository with test cases, each test case has steps with an "action" field and an "expected result" field 
<img width="933" alt="Screenshot 2023-11-29 at 17 07 44" src="https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/2599742/f2c789ad-520e-4958-9441-d78b6077ebce">

When I run this plugin, it creates me new issue with the test result 
<img width="1066" alt="Screenshot 2023-11-29 at 17 10 40" src="https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/2599742/6ccf9853-57ef-4fe7-83b1-377d1fb39d63">

But after running  my test case steps are removed: 
<img width="1061" alt="Screenshot 2023-11-29 at 17 12 15" src="https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/2599742/6ee93c1b-07c7-4649-8597-b1f4bdad50b8">
  and there are no additional information in "x-ray history" tab in Jira. 

I found this pr https://github.com/Qytera-Gmbh/cypress-xray-plugin/pull/229/files#diff-58fe231e03338f09421bfe4d990494b89b13ad3d3d31677a6170ba820f7243f1

And my question is, Is it expected behavior? Is there any way to not remove steps from the issue? Or maybe I'm using the plugin in the wrong way?

### Cypress version

^12.15.0

### Plugin version

5.2.1

### Jira/Xray type

Cloud

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment]
Hey @art-emm,

thanks for creating the issue. I just tested it in a new project and was unable to reproduce it. My steps did not disappear:

https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/2b8855c5-7f1a-4cbf-869c-ec38bb608528

As to the pull request you mentioned, that's unfortunately simply one for internal code clean up. It has nothing to do with cleaning up "real" repositories. Issue #209 might be related. This one was fixed, however.

So something is different in your configuration. Are you sure you're using version 5.2.1 of the plugin? You could try reinstalling the plugin to absolutely make sure (or just check the plugin's `package.json` inside the `node_modules` directory):

```sh
npm uninstall cypress-xray-plugin
npm install --save-dev cypress-xray-plugin
```

Maybe this fixes things already. Otherwise we would need to dig into the requests you send to Xray, but let's try the simple fix first.

**Comment by art-emm** [comment]
@csvtuda Thank you a lot for your help. After full reinstallation of `node_modules` it began to work as expected.
