### ISSUE TITLE
Is it possible to associate a Cucumber scenario's automatically created test ticket with a Jira Story?

### ISSUE THREAD

**Issue by atddkg** [Qytera-Gmbh/cypress-xray-plugin#336]
Hi,

Apologies if this is a noob question, it's been a long day of reading guides and troubleshooting, my mind is gone. I don't remember seeing anything suggesting that your plugin supports [this](https://docs.getxray.app/display/XRAYCLOUD/Importing+Cucumber+Tests+-+REST)...

> @REQ_CALC-1910
> Feature: As a user, I can calculate the sum of two numbers

Thanks

**Comment by csvtuda** [comment]
Hi @atddkg,

thanks for asking. I think the answer to your question is yes and no.

### Yes

The plugin can upload Cucumber scenarios (import Cucumber tests), as described [here](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/guides/featureFileSynchronization/#feature-file-upload). To do so, you'll need to configure the plugin as follows:

```ts
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";
import * as createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import { configureXrayPlugin, syncFeatureFile } from "cypress-xray-plugin";
import fix from "cypress-on-fix";

async setupNodeEvents(on, config) {
    const fixedOn = fix(on);
    await configureXrayPlugin(on, config, {
            // ...
            cucumber: {
                featureFileExtension: ".feature",
                uploadFeatures: true
            }
        }
    );
    await addCucumberPreprocessorPlugin(fixedOn, config);
    fixedOn("file:preprocessor", async (file) => {
        await syncFeatureFile(file); // <<< make sure to include this function call
        const cucumberPlugin = createBundler({
            plugins: [createEsbuildPlugin(config)],
        });
        return cucumberPlugin(file);
    });
    return config;
}
```

### No

In your title, you asked about _a Cucumber scenario's automatically created test ticket_. The plugin never creates test tickets automatically. The only thing the plugin is allowed to create are test execution issues, but never tests or preconditions. So it's therefore _not_ possible to link Cucumber scenarios to automatically created test tickets since they are never created automatically.

In #335 you described your IDE as the source of truth, but the plugin assumes Jira/Xray to be the source of truth. Therefore, you'll need to create test/precondition tickets manually for new Cucumber scenarios, copy their Jira issue keys and paste them as Cucumber tags in your feature files.

Let me know if this helped you or if you have further questions.

**Comment by atddkg** [comment]
Your response has been confusing the hell out of me but I think I know why.

It appears your plugin merely uploads the feature files to [Xray's API](https://docs.getxray.app/display/XRAYCLOUD/Importing+Cucumber+Tests+-+REST) but it's actually Xray that decides what to do with it?...

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/169905511/9150a7d0-eec5-4214-b88f-7ac94b704966)

Via your plugin, I've been automatically creating test tickets from newly authored local scenarios all day, but I understand now that your plugin isn't doing the ticket-creation part, Xray is.

My confusion was borne out of conflation between what your plugin does and what Xray does with the uploaded feature files. Simply because you both have 'Xray' in your names! Apologies.

I guess the answer's still the same but to visualise/confirm what I was looking to achieve:

![image](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/169905511/11d4a80f-20a6-42fe-8f3f-cd739653c0ba)

I wanted the Xray-automatically-created Test ticket TST-3 to be automatically associated/linked to, in this instance, Story ticket TST-2. I guess it's more of a question to pose to Xray?

**Comment by csvtuda** [comment]
Oh I see, I absolutely get that this is confusing. And you're right, Xray is creating these issues automatically. I should have phrased that better.

> Simply because you both have 'Xray' in your names! Apologies.

I mean the plugin is pretty much built for Xray only, so it made sense to me to put Xray in its name. But it's not an official one.

> I wanted the Xray-automatically-created Test ticket TST-3 to be automatically associated/linked to, in this instance, Story ticket TST-2. I guess it's more of a question to pose to Xray?

It _should_ be possible to do that by adding a requirement tag as described [here](https://docs.getxray.app/display/XRAY/Importing+Cucumber+Tests+-+REST):

![requirement linking](https://github.com/Qytera-Gmbh/cypress-xray-plugin/assets/18561435/f8aa71dc-1294-4522-80d5-25e7cdff6877)

In your case, you might achieve that with a `@Requirement:TST-2` tag - depending on your [prefix configuration](https://docs.getxray.app/display/XRAYCLOUD/Global+Settings%3A+Cucumber).

**Comment by atddkg** [comment]
Because my head was so deep in the weeds, and now I've slept and zoomed out, I had already tried `@REQ_TST-2` above the feature and it didn't work (coincidentally found out this morning that my Cucumber Export Prefixes had `Requirement` set to `REQ_`). Perhaps this is a symptom of [another issue I'm having](https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/337).

> I mean the plugin links Cypress and Xray exclusively, so it made sense to me to put Xray in its name. But it's not an official plugin, I only got lucky with the name.

Problem exists between keyboard and chair (me) lol
