### ISSUE TITLE
Failed to import execution: Request failed with status code 400

### ISSUE THREAD

**Issue by emsalmengus** [Qytera-Gmbh/cypress-xray-plugin#365]
### Description

Hello all,

we have successfully integrated the cypress-xray-plugin with version 7.1.0 and Cypress 13.13.1 according to the documentation. However, new cypress tests are not uploaded into Xray. This is true for both when test issue key is included in the title or not. Only by naming test issue keys that already exist in Xray, cypress test results are uploaded.

The authentication works:
```

Jira PAT found. Setting up Jira server PAT credentials.
Jira PAT found. Setting up Xray server PAT credentials.

But when uploading the results, we get the error message:

Importing Cypress execution...
Failed to import execution: Request failed with status code 400
Complete error logs have been written to: C:\Users\...
Encountered problems during plugin execution! C:/Users/...
Skipping result upload.
......
.....
No test results were uploaded
Failed to upload Cypress execution results.
Caused by: Failed to convert Cypress tests into Xray tests: No Cypress tests to upload
```

We want to upload new Cypress tests that are not existing in Xray yet. Could you please check this issue out?

Thank you very much.

Best wishes,
Emsal

### Cypress version

13.13.1

### Plugin version

7.1.0

### Jira/Xray type

Server

### Configuration

```ts
const { defineConfig } = require("cypress");
const { configureXrayPlugin } = require ("cypress-xray-plugin");


module.exports = defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {
      await configureXrayPlugin(
        on,
        config,
        {
          jira: {
            projectKey: "***",
            url: "https://****************************(this is our internal jira base url)",
            /*testExecutionIssueKey: "***",*/
            attachVideos: true
          },
          xray: {
            uploadResults: true,
            uploadScreenshots: true,
            uploadRequests: true
          }
        }
      );
    }
  }
});
```

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment]
Hey @emsalmengus,

thanks for raising this issue.

> Only by naming test issue keys that already exist in Xray, cypress test results are uploaded.

To me, it sounds like there are two things going on that are causing you trouble, both of which are actually intended by design.

- _No Xray tests created for untagged Cypress tests_: The plugin refuses to upload results for tests that don't exist in Jira (i.e. tests without issue keys in the title). You should hopefully see warnings for these.
  - Why is this not possible? It _was_ possible in the past and it caused a lot of difficult to solve problems ([#47](https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/47), [#83](https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/83), [#84](https://github.com/Qytera-Gmbh/cypress-xray-plugin/issues/84)), which is why I decided to remove this feature in [4.0.0](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#breaking-changes-3). The plugin will only work properly/as intended if you treat Xray as the source of truth for test issues.
  - What can you do about this? Unfortunately, for new tests, you will have to manually create the test in Xray and then copy the test issue key to the Cypress test.

- _No results uploaded even though you've tagged everything_: Based on the `Failed to import execution: Request failed with status code 400` line in your logs, I assume you have tagged every test but the upload still failed. One way to end up with 400 Bad Request is to link Cypress results to non-existent Xray test issues. Xray will then be unable to match the uploaded results and will return a corresponding 400 Bad Request.
  - If this is not what you were trying to do, please enable [`debug` mode](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/plugin/#debug) and look into the returned response, it usually contains a more detailed explanation as to why the 400 Bad Request occurred.
