### ISSUE TITLE
Option to upload screenshot as attachment instead of evidence ?

### ISSUE THREAD

**Issue by ndup0nt** [Qytera-Gmbh/cypress-xray-plugin#411]
Hi,

Many thanks for this plugin I experiment in my company. Unfortunately, screenshots upload is not working. I have no error but cannot see them in the test execution. I wonder if this is because my Xray instance is an old version.

As an alternative, would it be possible to upload the screenshots as attachments instead of evidence (like the videos upload, which is working) ?

**Comment by csvtuda** [comment]
Hi @ndup0nt,

thanks for the issue. I assume you're using Jira/Xray server? If yes, do you know which Jira and Xray version you're using?

There are a few things I would like you to double check for now.

- Which plugin version are you using?
- Are [screenshot uploads](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/xray/#uploadscreenshots) enabled?
- Is Cypress actually taking screenshots?
- Are there any warnings in the plugin's output regarding screenshots that cannot be attributed to tests?

**Comment by csvtuda** [comment]
That's good information, thanks a lot. There might be a compatibility issue with your Jira/Xray versions, according to this matrix:

https://marketplace.atlassian.com/apps/1211769/xray-test-management-for-jira/version-history

![compatibilities](https://github.com/user-attachments/assets/cc5efe4e-6ead-4f0a-9f65-7a8b72085ac5)

I recently had a client with a similar issue where Xray simply would not update existing test executions. This was also because the versions used were incompatible. An Xray update then solved the problem.

**Comment by ndup0nt** [comment]
Hello @csvtuda, my apologies, it turns out I just didn’t know where to look for the evidence in XRay. However, an XRay specialist helped me find them, and we can indeed see the screenshots there. Thanks again for your help.
