### ISSUE TITLE
Upload runner test execution timings

### ISSUE THREAD

**Issue by joe-noumena** [Qytera-Gmbh/cypress-xray-plugin#412]
Hey, 

Wondering if its possibly to upload the actual run test execution timings and stats table? Maybe it's already possible and I missed it. 

Cheers,
Joe

**Comment by csvtuda** [comment]
Hi @joe-noumena,

thanks for the input.

> the actual run test execution timings

Do you mean for the overall test execution, i.e. how long it took Cypress to run the tests from start to finish?

> stats table

Can you clarify on what you mean by that?

**Comment by joe-noumena** [comment]
Basically the output the cypress itself generates during a run could be useful metrics to have in x-ray / jira

**Comment by csvtuda** [comment]
If you want to add such a run summary to the description of the test execution issue, you can do this already:

```ts
await configureXrayPlugin(fixedOn, config, {
    jira: {
        projectKey: "CYP",
        url: "https://example.atlassian.net",
        testExecutionIssue: ({ results }) => {
            const totalMinutes = Math.floor(results.totalDuration / 1000 / 60);
            const totalSeconds = Math.round(results.totalDuration / 1000 / 60);
            const resultSummary = `
                Total execution time: ${totalMinutes}:${totalSeconds}

                ${results.runs
                    .map((run) => {
                        const duration = run.stats.duration ?? 0;
                        const specMinutes = Math.floor(duration / 1000 / 60);
                        const specSeconds = Math.round(duration / 1000 / 60);
                        const tests = `${run.stats.tests} tests`;
                        const passing = `${run.stats.passes} passing`;
                        const failing = `${run.stats.failures} failing`;
                        const pending = `${run.stats.pending} pending`;
                        const skipped = `${run.stats.skipped} skipped`;
                        return `${run.spec.name} | ${specMinutes}:${specSeconds} | ${tests} | ${passing} | ${failing} | ${pending} | ${skipped}`;
                    })
                    .join("\n")}
            `;
            return {
                fields: {
                    description: resultSummary,
                    // begin date
                    customfield_10029: new Date(results.startedTestsAt).toISOString(),
                    // end date
                    customfield_10030: new Date(results.endedTestsAt).toISOString(),
                },
            };
        },
    },
});
```

This will create a description that looks something like this:

![description](https://github.com/user-attachments/assets/a864750e-d1e4-43a7-92a7-bc9d209b5a1c)

As far as I know, the Xray import endpoint unfortunately does not support [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/) (see [this](https://community.atlassian.com/t5/Marketplace-Apps-Integrations/Re-Re-Cannot-create-a-test-because-description-not-acce/qaq-p/2368837/comment-id/99996#M99996) corresponding discussion), so creating "actual tables" is not possible, you will need to format your table using whitespace.

**Comment by joe-noumena** [comment]
@csvtuda I see thanks so much for the info makes sense.
