### ISSUE TITLE
Test type isn't updating

### ISSUE THREAD

**Issue by PranavHiraniAI** [Qytera-Gmbh/cypress-xray-plugin#430]
### Description

I am using     "cypress-xray-plugin": "7.1.0",       "cypress": "^13.15.2",
 and i have added
 ```
         jira: {
          fields: {
            labels: config.env.JIRA_FIELDS_LABELS,
            testType: config.env.JIRA_FIELDS_TEST_TYPE,
          },
          projectKey: config.env.JIRA_PROJECT_KEY,
          url: config.env.JIRA_URL,
        },
 ```       
in my cypress config
        
and also added  JIRA_FIELDS_LABELS, and JIRA_FIELDS_TEST_TYPE in env
        
but it is not updating the test type or adding labels to the test 
(the test Is precreated and I am tagging the issue key in bdd scenario in .feature files)
       
it is creating testexecutions and linking to the precerated tests but not updating the test type
       
       

### Cypress version

13.15.2

### Plugin version

7.1.0

### Jira/Xray type

Cloud

### Configuration

```ts
import { defineConfig } from 'cypress';
import createBundler from '@bahmutov/cypress-esbuild-preprocessor';
import { addCucumberPreprocessorPlugin } from '@badeball/cypress-cucumber-preprocessor';
const createEsbuildPlugin =
  require('@badeball/cypress-cucumber-preprocessor/esbuild').createEsbuildPlugin;
import { configureXrayPlugin, syncFeatureFile } from 'cypress-xray-plugin';
import fix from 'cypress-on-fix';

export default defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {
      const fixedOn = fix(on);
      await addCucumberPreprocessorPlugin(fixedOn, config);
      await configureXrayPlugin(fixedOn, config, {
        cucumber: {
          featureFileExtension: '.feature',
          downloadFeatures: true,
        },
        jira: {
          fields: {
            labels: config.env.JIRA_FIELDS_LABELS,
            testType: config.env.JIRA_FIELDS_TEST_TYPE,
          },
          projectKey: config.env.JIRA_PROJECT_KEY,
          url: config.env.JIRA_URL,
        },
      });
      fixedOn('file:preprocessor', async (file) => {
        await syncFeatureFile(file);
        const cucumberPlugin = createBundler({
          plugins: [createEsbuildPlugin(config)],
        });
        return cucumberPlugin(file);
      });
      return config;
    },
    specPattern: 'e2e/**/*.feature',
    supportFile: 'support/e2e.ts',
    env: {
      tags: '@automated',
      localePath: '../packages/common/contexts/localization/locales/en.json',
    },
  },
  chromeWebSecurity: false,
});
```

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment]
Hey @PranavHiraniAI,

thanks for the issue. I'm not yet entirely sure what you're trying to do, so here are two suggestions.

---

If you want to configure test _execution_ data such as labels, you'll need to use the [`testExecutionIssue`](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/configuration/jira/#testexecutionissue) setting:

```js
      await configureXrayPlugin(fixedOn, config, {
        // ...
        jira: {
          testExecutionIssue: {
            fields: {
              labels: config.env.JIRA_FIELDS_LABELS // must be an array of strings
            }
          },
        // ...
        },
      });
```

These will then be added to the test execution issue.

You can customize any field there that is present in your test execution issues (assignee, ...). 

---

If you want to add labels to your _test issues_, you'll need to stick to [Xray's Cucumber documentation](https://docs.getxray.app/display/XRAYCLOUD/Importing+Cucumber+Tests+-+REST+v2) and add them to your scenarios inside the feature files. Xray will then add them to your test issues on feature file import (i.e. `syncFeatureFile`). 

The plugin _does not_ add them to your tests automatically, neither does it update the test type. You _will_ need to change the test type in Xray on your own.

**Comment by csvtuda** [comment]
I see.

> If not labeled it is fine

The example tagged `@automated` you've provided should be labelled on feature file upload according to Xray: _The tags used in the scenario/scenario outline are also added as labels._

If this is not the case you might want to file a bug with Xray :thinking: Unless it's because you're importing test results of type Cucumber to tests that are not of type Cucumber. That might also be an issue.

> so the Test Type of test issues related to that scenarios should be updated to Automated

To be honest, allowing the plugin to change test types would open a huge can of worms:
- The plugin currently does not modify test issues. It only modifies or creates test execution issues. It _was_ able to create and update test issues in the past, but that lead to a lot of confusion, complicated configurations and other issues, e.g.:
  - #83
  - #84
  - #100
- The configurability would be complicated, as it would need to support different test types for Cypress and/or Cucumber tests.
- Changing test types can be an _extremely_ destructive action if the test type provided in the plugin is not of the same category like the ones currently configured, deleting _all_ steps/test definitions. Not a good idea from a perspective of the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

---

In my opinion it's too difficult for me to provide a one-fits-all solution that will make all users happy. Therefore, I suggest you implement your use case "manually" with a custom hook:

```ts
export default defineConfig({
  e2e: {
    async setupNodeEvents(on, config) {
      const fixedOn = fix(on);
      await addCucumberPreprocessorPlugin(fixedOn, config);
      // New hook: 
      // 1. Identify all tests we want to update
      // 2. Update all test types using the Xray API
      fixedOn("after:run", async (results) => {
          if ("status" in results) {
            // Return early if Cypress failed to run.
            return;
          }
          // Identify all relevant test issues whose test types we want to update.
          const issueKeys = new Set<string>();
          const projectKey = "CYP";
          // Matches as follows:
          // "CYP-123 CYP-456 hello test"
          // [ "CYP-123", "CYP-456" ]
          const titleRegex = new RegExp(`(${projectKey}-\\d+)`, "g");
          for (const run of results.runs) {
            for (const test of run.tests) {
              if (shouldUpdateTestType(run, test)) {
                const testKeys = test.title.join(" ").match(titleRegex);
                if (testKeys) {
                  testKeys.forEach((key) => issueKeys.add(key));
                }
              }
            }
          }
          await updateTestTypes("Automated", ...issueKeys);
        }
      );
      // Make sure to add the plugin afterwards such that the plugin's hooks run after
      // the one that updates the test types.
      await configureXrayPlugin(fixedOn, config, { /* ... */ });
      fixedOn('file:preprocessor', async (file) => { /* ... */ });
      return config;
    },
    specPattern: 'e2e/**/*.feature',
    supportFile: 'support/e2e.ts',
    env: {
      tags: '@automated',
      localePath: '../packages/common/contexts/localization/locales/en.json',
    },
  },
  chromeWebSecurity: false,
});

/**
 * Returns whether the specified test should be included in the tests to update.
 *
 * @param run the Cypress run
 * @param test the test included in the Cypress run
 * @returns `true` if it should be updated, `false` otherwise
 */
function shouldUpdateTestType(run: CypressCommandLine.RunResult, test: CypressCommandLine.TestResult) {
  const projectKey = "CYP";
  // Custom logic, e.g. only update test types of tests in normal Cypress specs:
  return run.spec.fileExtension.endsWith(".js") && test.title.join(" ").includes(projectKey);
}

/**
 * Sets the test type of all provided issues to the specified one if needed.
 *
 * @param testType the target test type
 * @param issueKeys the issues whose test type should be updated
 */
async function updateTestTypes(testType: string, ...issueKeys: string[]) {
  // 1. Authenticate to Xray Cloud API
  //    - https://docs.getxray.app/display/XRAYCLOUD/Authentication+-+REST+v2
  // 2. Update test type for each identified test issue
  //    - https://us.xray.cloud.getxray.app/doc/graphql/updatetesttype.doc.html
  const authenticationResponse = await fetch("https://xray.cloud.getxray.app/api/v2/authenticate", {
    method: "POST",
    headers: { ["content-type"]: "application/json" },
    body: JSON.stringify({
      client_id: ...,
      client_secret: ...,
    }),
  });
  const token = await authenticationResponse.json();
  const issues = await getTestIssues(token, ...issueKeys);
  for (const issue of issues) {
    // Skip tests whose test type has been updated already.
    if (issue.testType.name === testType) {
      continue;
    }
    const response = await fetch("https://xray.cloud.getxray.app/api/v2/graphql", {
      method: "POST",
      headers: { authorization: `Bearer ${token}`, ["content-type"]: "application/json" },
      body: JSON.stringify({
        query: `
          mutation {
            updateTestType(issueId: "${issue.issueId}", testType: { name: "${testType}" }) {
              testType {
                name
              }
              jira (fields: ["key"])
            }
          }
        `,
        variables: {},
      }),
    });
    // The response will looke like this:
    // {
    //   data: {
    //     updateTestType: {
    //       testType: { name: "Automated Steps" },
    //       jira: { key: "CYP-1139" },
    //     },
    //   },
    // };
    const json = await response.json();
    console.log(`Updated test type: ${json.data.updateTestType.jira.key} - ${json.data.updateTestType.testType.name}`);
  }
}

/**
 * Returns test issue data for the specified issue keys.
 *
 * @param issueKeys the issue keys
 * @returns the corresponding issue issue data
 */
async function getTestIssues(token: string, ...issueKeys: string[]) {
  const issues: { issueId: string; testType: { name: string } }[] = [];
  // GraphQL limit ist 100 by default.
  const limit = 100;
  for (let i = 0; i < issueKeys.length; i += limit) {
    const jql = `issue in (${issueKeys.slice(i, i + limit).join(",")})`;
    const query = `
      {
        getTests(limit: ${limit}, jql: "${jql}") {
          results {
            issueId
            testType {
              name
            }
          }
        }
      }
    `;
    const response = await fetch("https://xray.cloud.getxray.app/api/v2/graphql", {
      method: "POST",
      headers: { authorization: `Bearer ${token}`, ["content-type"]: "application/json" },
      body: JSON.stringify({ query: query, variables: {} }),
    });
    // The response will look like this:
    // {
    //   "data": {
    //     "getTests": {
    //       "results": [
    //         {
    //           "issueId": "13747",
    //           "testType": {
    //             "name": "Manual"
    //           }
    //         }
    //       ]
    //     }
    //   }
    // }
    const json = await response.json();
    for (const result of json.data.getTests.results) {
      issues.push(result);
    }
  }
  return issues;
}
```

**Comment by PranavHiraniAI** [comment]
@csvtuda thankyou for your response and providing the apis for updating test types manually
The issue has been solved but the only thing pinning to me is that,
Why the customization features like this got removed in recent versions?
Because I see there is great customizations available in older versions,
that is missing in latest ones and removed even from the documentation.
Isn't it better to give high level of customization to the users so they can configure it like they want.
JUST A SUGGESTION.

**Comment by csvtuda** [comment]
Thanks for the feedback! I agree that especially the documentation should probably be available in a version-specific fashion. It's something I have never really managed to thoroughly investigate.

>  Why the customization features like this got removed in recent versions?

It basically boils down to me not being able to adequately model Xray's behaviour in the plugin. Consider the removed `jira.createTestIssues` option, for example. It allowed the creation of new test issues for tests without issue keys in their title. Pretty cool. But the issues created that way are identified and compared by their summary in Xray when uploading results. You're uploading results after you've renamed the test case in Cypress? You'll get a new test issue in Jira. The Jira board owner decided to add a `QA: ` prefix to all test issues? You'll get a lot of new test case issues without the prefix unless you rename all test cases in Cypress.

Obviously this can be prevented by adding issue keys to the Cypress test titles for the plugin to find. Or by setting `jira.createTestIssues` to `false`, right? No, unfortunately not. The Cucumber feature file upload does not care about that. It's even worse because Xray tries to match scenarios to existing test issues [as follows](https://docs.getxray.app/display/XRAYCLOUD/Importing+Cucumber+Tests+-+REST+v2):

> If Test key is not present in the file, system tries to find the Test having: the same source and original relative path of .feature (e.g. "[project_lambda]core/sample_addition.feature) [...]

So if you _rename_ your feature file or any of the directories it's contained in, you'll often end up with new test cases on feature file upload. Even if the plugin is explicitly told not to do that. Moreover, if you've tagged all Gherkin scenarios with issue keys, the upload can _still_ create new issues if the tagging scheme is modified in Xray (i.e. scenario and precondition prefixes).

It is basically impossible for the plugin to _prevent_ issues from being created, because Xray does a lot of things behind the scenes. So why keep such an option that will only confuse users (see linked issues above) and is a pain in the butt for me to maintain?

That's why I decided that the plugin should always consider Xray as the single source of truth for the time being. No more test issue updating (the feature file upload is an exception to this and has blown up the plugin's complexity over time, unfortunately). The plugin is only allowed to create or modify test execution issues. It's basically become a reporter.

**Comment by PranavHiraniAI** [comment]
@csvtuda Thanks again for understandable clarification and being helpful.
