### ISSUE TITLE
Passing the test body as the action can result in failed uploads

### ISSUE THREAD

**Issue by barnes** [Qytera-Gmbh/cypress-xray-plugin#50]
In the getTestInfo function, by default the test body as the 'action', which can fail uploading with larger / complex test code. Not sure if there is a better value to place here, or a way to treat the test body string to prevent these failures.

**Comment by csvtuda** [comment]
### Xray cloud
The action length limits for Xray cloud seem to be:
- API: 8192 characters
- Web UI: 8188 characters

Interestingly, once _more_ than 8188 characters are passed via API, it's impossible to alter the action in the UI afterwards.

### Xray server

In my Xray server instance, I stopped trying after:
- API: 4 194 304 (2^22) characters, which the API still accepted just fine (took 40 seconds though)
- Web UI: crashed my page (out of memory) when trying to insert 2 097 152 (2^21) characters

I don't think there's a non-technical limit for Xray server.

To actually address the issue: I don't really know what to put there either, since Cypress does not really have a notion of a _step_.

I think the following would be a reasonable solution:
- pass the test body by default
- allow users to pass a custom function to the configuration section where they can define what to pass to the `action` property
- truncate every action to 8192 characters and display a warning if characters had to be removed
